language: ruby
cache: bundler
rvm:
  - 2.4.1
services:
  - postgresql
env:
  - RAILS_ENV=test
before_install:
  - gem install bundler
script:
  - bundle exec rubocop
  - bundle exec rake db:create db:migrate
  - bundle exec rspec spec
