default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgres://postgres:@localhost:5432/potmum_development' %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgres://postgres:@localhost:5432/potmum_test' %>

production:
  url: <%= ENV['DATABASE_URL'] %>
